# Generated by Django 5.0.1 on 2024-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('sms_code', models.CharField(blank=True, default='', max_length=10)),
                ('record_at', models.DateTimeField(auto_now=True)),
                ('recovery_token', models.CharField(max_length=50, null=True)),
                ('bad_code_count', models.IntegerField(blank=True, default=0)),
                ('bad_code_init_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
