# Generated by Django 5.0.1 on 2024-06-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_temporaryuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryuser',
            old_name='sms_code',
            new_name='otp',
        ),
    ]
